In [ ]:
import numpy as np


# 실습 과제1: NumPy를 활용한 행렬 변형 실습

## 문제 1: 난수 행렬 생성
N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
힌트: np.random.rand() 함수를 사용하세요.


In [2]:
import numpy as np

In [23]:
np.random.seed(0)

A = np.random.rand(6,5)
A

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194]])

## 문제 2: 새로운 축 추가

행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.

In [26]:
B = A[:, None, :]
B

array([[[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ]],

       [[0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152]],

       [[0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]],

       [[0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215]],

       [[0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443]],

       [[0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194]]])

문제 3: 슬라이싱을 이용한 특정 요소 변경
행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.

In [13]:
B[2, :, : ] = 0.3
B


array([[[0.39256695, 0.7054632 , 0.01507239, 0.42495469, 0.7439814 ]],

       [[0.24039554, 0.20720891, 0.44330802, 0.03284123, 0.96211827]],

       [[0.3       , 0.3       , 0.3       , 0.3       , 0.3       ]],

       [[0.26767252, 0.61955558, 0.00989235, 0.91572002, 0.84376389]],

       [[0.27017816, 0.67904693, 0.68155164, 0.60118505, 0.11799412]],

       [[0.68665606, 0.36854946, 0.05995789, 0.73505486, 0.3441927 ]]])


문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성
np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.

In [ ]:
C = A[np.newaxis, :, :]

C

array([[[0.39256695, 0.7054632 , 0.01507239, 0.42495469, 0.7439814 ],
        [0.24039554, 0.20720891, 0.44330802, 0.03284123, 0.96211827],
        [0.3       , 0.3       , 0.3       , 0.3       , 0.3       ],
        [0.26767252, 0.61955558, 0.00989235, 0.91572002, 0.84376389],
        [0.27017816, 0.67904693, 0.68155164, 0.60118505, 0.11799412],
        [0.68665606, 0.36854946, 0.05995789, 0.73505486, 0.3441927 ]]])

In [ ]:
D = A[:, :, None]
D

array([[[0.39256695],
        [0.7054632 ],
        [0.01507239],
        [0.42495469],
        [0.7439814 ]],

       [[0.24039554],
        [0.20720891],
        [0.44330802],
        [0.03284123],
        [0.96211827]],

       [[0.3       ],
        [0.3       ],
        [0.3       ],
        [0.3       ],
        [0.3       ]],

       [[0.26767252],
        [0.61955558],
        [0.00989235],
        [0.91572002],
        [0.84376389]],

       [[0.27017816],
        [0.67904693],
        [0.68155164],
        [0.60118505],
        [0.11799412]],

       [[0.68665606],
        [0.36854946],
        [0.05995789],
        [0.73505486],
        [0.3441927 ]]])


문제 5: 슬라이싱을 통해 부분 행렬 변경
행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.

In [ ]:
D[-3:-1,:,:] = 0.8

D

array([[[0.39256695],
        [0.7054632 ],
        [0.01507239],
        [0.42495469],
        [0.7439814 ]],

       [[0.24039554],
        [0.20720891],
        [0.44330802],
        [0.03284123],
        [0.96211827]],

       [[0.3       ],
        [0.3       ],
        [0.3       ],
        [0.3       ],
        [0.3       ]],

       [[0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ]],

       [[0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ]],

       [[0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ]]])

: 